### PR TITLE
python implementation of re-sampling algorithm

### PR DESCRIPTION
**Pull request by UHstudent**
This commit implements probability maps and fourier maps for detecting traces of resampling as explained in the paper: 
"Exposing Digital Forgeries by Detecting Traces of Re-sampling" by Hany Farid & Alin C. Popescu
The book "Photo Forensics" by Hany Farid gives a more detailed explanation of the technique for those interested

The interface is pretty user friendly, but could be improved upon.

Brief explanation on how the tool might be used for analysis: 

Upon opening the resampling tool, the image is displayed in grayscale. (re-sampling analysis must be done in grayscale in order to avoid CFA artifacts.)

left click on the image to select regions of interest to calculate the probability map; right click to remove last point.
if no region of interest is selected, the probability maps for the entire image is calculated when clicking the corresponding button.

In order to calculate fourier maps for a given area, switch the checkbox to "fourier Windows"

Analysis of fourier maps to verify periodic artifacts can be difficult, because JPEG compression artifacts are already visible at 98-99% quality and these periodic artifacts influence the visibility of other interpolation artifacts that might have been introduced through re-sizing,...
Further more, depending on the camera, an original picture at 0% compression might already have some type of periodic artifact.

To successfully use re-sampling for forensic analysis, it is advisable to compare fourier maps from different regions to the "general" fourier map of the entire picture.

local areas that were part of the original picture, should display a similar fourier map; where as manipulated regions might have a distinct fourier map and thus indicative of tampering/not being part of the original capture.

The probability map can also aide analysis, as similar regions should have a similar probability of being interpolated, when this is not the case, one region might be manipulated.

Different parameters to construct the fourier map have a huge impact on how periodic patterns might be perceived. Only compare fourier maps that have equal settings!

Uniform areas and different manipulations (compression, re-size, rotate,..) will disturb each others' periodic signals and make analysis more difficult.

### CODE REVIEW

**Comment by Ray9T** [comment]
Hello @UHstudent , @GuidoBartoli  It's exciting to watch newer theories getting integrated into this app. 
Question I have is, has this resampling method tested against known fabrications?
I have a set of images that the previous version clearly shows areas of fabrication, but from 0.89 version, those separations are less pronounced and very faded or blended in. 

Was this paper/theory tested against known fabrications, and can you share the image sources?

**Comment by UHstudent** [comment]
Hi @Ray9T 

Thanks for your interest in the developments to the project!

I've tested the resampling method extensively against real and manipulated images. (pictures taken by my cellphone and resized with cv2 library.) My general conclusion is that the compression artifacts generally overshadow resampling artifacts. For this reason, it is difficult to analyse most pictures since most camera's compress pictures automatically. 

One drawback to my own testing, is that my device only allowed uncompressed images to be taken in a ".dng" format. When converting this format to grayscale with rawpy, a periodic artifact is introduced and detected by the algorithm. I know the periodic artifact is introduced by rawpy, as changing the demosaic algorithm, changes the periodic output:
image

Haney Farid in his paper uses a dataset made by a device he owns that is able to shoot uncompressed ".tif" images. To my knowledge, this dataset has not been made publicly available.

I've also tested on the "standard" test images found here:
https://www.imageprocessingplace.com/root_files_V3/image_databases.htm

Depending on how the fourier map is constructed, the results of the original paper is almost perfectly replicated. Note that the paper mentions that it shows "the central part of the fourier map", but gives no clear instructions on when or how this part is taken.

Here follows the original (color) mandril, followed by 5, 10 and 20% upsampling:
image
image
image
image
image

To my knowledge, this is the first time the resampling algorithm has been enabled for execution in the project? So I'm not sure what you mean by different versions showing different results?

Finally, consider this analysis. A picture of a classroom made by a cellphone at 95% JPEG quality. A part of the top right has been taken, resized, and inserted in the bottom right (cv2 lib):
actualrisize

local analysis (hanning, upsample, Highpass 1, gamma correction 4, rescale spectrum):
localized analysis

global analysis, same parameters:
general analysis


Please let me know your thoughts and insights!

**Comment by Ray9T** [comment]
This is very cool, thank you for the details and sorry for the late response. I also sent you a message, in case you haven't had a chance to check. 
I can follow up with you privately regarding some issues with fabricated images that show heavy noise added to mask fabrications and a need to implement additional noise removal passes to improve detection, I'll share some research papers with you regarding this.

I can check with Hany on support for uncompressed images other than DNG, and we very likely need .tif and other popular uncompressed formats added to compat.

**Comment by UHstudent** [comment]
Hi, I've published my thesis which more extensively dives into how the resampling algorithm works and how it can be used for detecting manipulation, it starts on page 32:
https://github.com/UHstudent/digital_image_forensics_thesis/blob/main/Thesis%20text_Digital%20Image%20Forensics-A%20Comparative%20Study%20between%20AI%20and%20traditional%20approaches.pdf

further into the paper, I also discuss how the probability maps in isolation can be a useful technique for noise analyses, similar to the noise wavelet blocking technique.

The resampling algorithm, as implemented in Sherloq, functions on any image file that Sherloq can handle (jpg, png, tiff,...)

**Comment by Ray9T** [comment]
Congratulations on completion of your masters UHStudent, succesfully and publishing your thesis. 

Thank you for sharing it with us! I'm going to set a side sometime this weekend to read it.

**Pull request merged**
